### ISSUE TITLE
'vendorjs' errored after 23 s

### ISSUE THREAD

**Issue by solarianian** [waqastudios/inti-foundation#7]
Erros are from child theme, but same goes for the inti-foundation parent theme:

[16:37:31] 'vendorjs' errored after 23 s
[16:37:31] TypeError: file.isSymbolic is not a function
    at DestroyableTransform.normalize [as _transform] (C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\node_modules\vinyl-fs\lib\dest\prepare.js:31:15)
    at DestroyableTransform.Transform._read (C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\node_modules\duplexify\index.js:201:22)
    at doWrite (C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at Pumpify.Writable.write (C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\node_modules\readable-stream\lib\_stream_writable.js:322:11)
[16:37:31] 'build' errored after 23 s
[16:37:31] 'default' errored after 23 s
[16:37:31] The following tasks did not complete: foundationjs
[16:37:31] Did you forget to signal async completion?

any help would be much appreciated!

**Comment by monicasolis** [comment]
@solarianian 
Check your version of Gulp
Delete your node_modules and re-rerun npm install (or use [RimRaf](http://www.nikola-breznjak.com/blog/javascript/nodejs/how-to-delete-node_modules-folder-on-windows-machine/))

this might help!

**Comment by phated** [comment]
This project must use plugins that are incompatible with gulp 4.0.0-alpha.3 which had breaking changes over the previous alpha.  Please have your plugins upgrade for compatibility

**Comment by solarianian** [comment]
@monicasolis & @phated Thank you for your help!

Unfortunately, other then make sure that I have the latest version of nodejs for windows, I don't know what to do. I am new to this way of deving. 

So, after installing the latest nodejs and running in theme folder npm install and gulp commands, the error is: 'sass' errored after 539 ms. 

So, /dist/ from /library/ is not existing. 

Where can I find a good guide with what preparations need to be done before running the first _npm command_? 

Right now, my steps are:

1. nodejs command prompt - > cd my project folder > npm install (a lot of errors); then npm build; then gulp (as seen: https://github.com/waqastudios/inti-foundation/issues/6 )

C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink>gulp
[00:01:59] Failed to load external module @babel/register
[00:01:59] Requiring external module babel-register
[00:02:02] Using gulpfile C:\xampp\htdocs\dev\wp-content\themes\inti-kitchen-sink\gulpfile.babel.js
C:\Users\solarian\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Users\solarian\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Thank you!

**Comment by solarianian** [comment]
UPDATE (not solved yet)

after a visit to gulp & npn websites, I manage to update to latest versions for nodejs, npm and gulp.

But, after running npm install in my project folder, some errors occur:

gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2

gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python

npm ERR! Failed at the node-sass@3.13.1 postinstall script.

after running gulp command in project directory:
[09:09:26] The following tasks did not complete: foundationjs, vendorjs, images, copyFonts, copyStaticCss, editorSass
[09:09:26] Did you forget to signal async completion?

Should I install python and python2?

Thank you!
